version: '3.8'
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    depends_on:
      - frontend
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run preview
