[phases]
  [phases.preInstall]
  command = "cd  && rm -rf node_modules/.cache || true && npm install --no-cache"

  [phases.build]
  command = "cd  && npm run build"

  # Fase para el Frontend
  [phases.postInstall]
  command = "cd frontend && rm -rf node_modules/.cache || true && npm install --no-cache"

  [phases.postBuild]
  command = "cd frontend && npm run build"

[build]
cache = false  # Deshabilitar cache global de Nixpacks




