[phases]
  [phases.preInstall]
  command = "cd  && rm -rf node_modules && npm install"

  [phases.build]
  command = "cd  && npm run build"

  # Fase para el Frontend
  [phases.postInstall]
  command = "cd frontend && rm -rf node_modules && npm install"

  [phases.postBuild]
  command = "cd frontend && npm run build"

[build]
cache = false  # Deshabilitar cache global de Nixpacks

nodeVersion = "18"  # O la versión que necesites

[[services]]
name = "frontend"
http_port = 5173
source = "cd frontend"

[[services]]
name = "backend"
http_port = 4000
source = "src"



